### ISSUE TITLE
Select highligthing color for "jump-to-word" buttons

### ISSUE THREAD

**Issue by GoogleCodeExporter** [legege/searchwp#32] opened 2015-03-15 20:16 UTC
```
From an email: 

"For SearchWP it would be nice if you could right click on a search button
and select the highlight colour (or turn off highlighting and/or searching
for that word)"
```

Original issue reported on code.google.com by `legege` on 2 Jul 2008 at 2:50

**Comment by Ede123** [comment] 2015-03-17 02:23
Duplicate of issue #23.

**Closed by Ede123** 2015-03-17 02:23 UTC
Labels: auto-migrated, Component-Tokens, Priority-Low, Type-Enhancement
